### ISSUE TITLE
thirdpartylibs.xml missing

### ISSUE THREAD

**Issue by danmarsden** [mattporritt/moodle-fileconverter_librelambda#1]
libre/lambda dirs appear to contain external (non-moodle) 3rd party code - looks like at least one is an example from AWS docs (not sure how that is licensed) - but any 3rd party code (with associated license info) needs to be added to the thirdpartylibs.xml file.

**Comment by danmarsden** [comment]
It would also probably be good to add a readme to the libre folder that helps describe what that file is, what it does etc.

**Comment by mattporritt** [comment]
441c1d2a2a69864d7 Fixes this
