### ISSUE TITLE
Does convert_submissions task really need to run on every cron?

### ISSUE THREAD

**Issue by danmarsden** [mattporritt/moodle-fileconverter_librelambda#3]
convert_submissions task is set by default to run every minute - is this really needed considering when a teacher opens an assignment it should trigger a conversion if one doesn't already exist?

**Comment by mattporritt** [comment]
The idea here is to get the converted documents in the background in a timely fashion, prior to the teach needing them to grade.

A teacher opening an assignment for grading triggers a blocking call to check to check for the converted document. If the document hasn't already been fetched by the the scheduled task then a synchronous call is made from Moodle to the output S3 bucket in AWS to check and download the file.

Running the task frequently means that this blocking call to AWS will happen rarely. If there are no pending conversions then this task will exit quickly.

**Comment by danmarsden** [comment]
I don't have a problem with it being set to "frequently" - I'm just not convinced it really needs to run "on every single cron run." - sites could have cron set to run every 30sec - or even more frequently - Personally I would think this particular task wouldn't need to run more often that 5min - It's unlikely a teacher will be sitting in front of the machine waiting for a student to upload a file and then want to grade it straight away - and if they are, running the conversion on load would probably be sufficient.

in any case - feel free to ignore me and just leave it as-is. :-)
