### ISSUE TITLE
improve info on compiled binaries

### ISSUE THREAD

**Issue by danmarsden** [mattporritt/moodle-fileconverter_librelambda#4]
the plugin includes some pre-compiled libre binaries, with a readme here:
https://github.com/mattporritt/moodle-fileconverter_librelambda/blob/master/libre/readme_moodle.txt

Ideally I'd like to see this readme include information on where these binaries are from, how to obtain these/compile them rather than blindly trust they are ok.

**Comment by mattporritt** [comment]
@danmarsden I've now added a pretty big set of instructions on how to compile these binaries yourself, plus some more general info.
This should sort this out
